### ISSUE TITLE
Abstract the population replacement mechanism

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/eva#24]
Right now, each new generation of solutions completely replaces the previous one. It would be nice to make this configurable .

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/170800f1-40d8-4386-9464-dd38e6e6c1b5.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/170800f1-40d8-4386-9464-dd38e6e6c1b5.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/77a1026e-6e9e-4060-95b9-f752ad8e4dc8.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/77a1026e-6e9e-4060-95b9-f752ad8e4dc8.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/47ac1ae3-8d3e-49b8-b570-5f40d8dc7ddf.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Index command executed successfully! 
 Add the following script to the website in order to make the search functionality available:

 &lt;script src=&quot;#&quot;&gt;eva&lt;/script&gt; 

 See [logs](http://charles.amihaiemil.com/logs.html?log=/47ac1ae3-8d3e-49b8-b570-5f40d8dc7ddf.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-github-ejb/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index pls

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index please

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index please

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete eva index

**Comment by charlesmike** [comment]
> @charlesmike delete eva index

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index  please

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index  please

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index 

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/468be783-70ef-40ab-a398-f65e66ec8630.log).

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil the `eva` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/468be783-70ef-40ab-a398-f65e66ec8630.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-github-ejb/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike delete eva index

**Comment by charlesmike** [comment]
> @charlesmike delete eva index

@amihaiemil the repository's name in a delete command has to be between single back apostrophes.
and it has to match the actual reponame exactly (case sensitive) 

A valid delete command here is ``@charlesmike delete `eva` index``.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/cf5be3fd-8eef-441b-8a4a-d5aba2d18f18.log).

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/cf5be3fd-8eef-441b-8a4a-d5aba2d18f18.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike delete `eva` index

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/67863149-7346-463f-bb27-978285365b80.log).

**Comment by charlesmike** [comment]
> @charlesmike delete `eva` index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/67863149-7346-463f-bb27-978285365b80.log) for details.

**Comment by amihaiemil** [comment]
@rultor config

**Comment by amihaiemil** [comment]
done
